#! /bin/bash

#Update the server
sudo apt update
sudo apt install apt-transport-https

#Install OpenJDK 11
sudo apt install openjdk-11-jdk -y

#Download and install public signin-key
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
sudo apt-get update

#Install Elasticsearch
sudo apt-get install elasticsearch
sudo systemctl start elasticsearch
sudo systemctl enable elasticsearch

#Install Logstash
sudo apt-get install logstash
sudo systemctl start logstash
sudo systemctl enable logstash

#Install Kibana
sudo apt-get install kibana
sudo systemctl start kibana
sudo systemctl enable kibana

#Install Filebeat
sudo apt-get install filebeat
sudo systemctl start filebeat
sudo systemctl enable filebeat