#! /bin/bash

#Update the server
sudo apt update
sudo apt install apt-transport-https

#Install OpenJDK 11
sudo apt install openjdk-11-jdk -y

#Download and install public signin-key
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
sudo apt-get update

#Install Elasticsearch
sudo apt-get install elasticsearch
sudo systemctl start elasticsearch
sudo systemctl enable elasticsearch

#Install Logstash
sudo apt-get install logstash
sudo systemctl start logstash
sudo systemctl enable logstash

#Install Kibana
sudo apt-get install kibana
sudo systemctl start kibana
sudo systemctl enable kibana

#Install Filebeat
sudo apt-get install filebeat
sudo systemctl start filebeat
sudo systemctl enable filebeat

#install metricbeat
curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.10.4-amd64.deb
sudo dpkg -i metricbeat-8.10.4-amd64.deb

#install Docker Engine
sudo su
apt-get update
apt-get install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository \
"deb [arch=amd64] https://download.docker.com/linux/ubuntu \
$(lsb_release -cs) \
stable"
apt-get update
apt-get install -y docker-ce
usermod -aG docker Ubuntu
chmod 666 /var/run/docker.sock
